transform_type: 'lifting'
transform_name: "HypergraphNodeCentralityLifting"
network_type: 'weighted'
alpha: 0.85
th_percentile: 0.05
n_most_influential: 2
do_weight_hyperedge_influence: False
do_hyperedge_node_assignment_feature_lifting_passthrough: False
max_iter: 100
tol: 1e-06
feature_lifting: ProjectionSum