transform_type: 'lifting'
transform_name: "HypergraphPageRankLifting"
network_type: 'weighted'
alpha: 0.85
th_quantile: 0.95
n_most_influential: 2
max_iter: 100
tol: 1e-06
feature_lifting: ProjectionSum