data_domain: pointcloud
data_type: toy_dataset
data_name: gudhi_sphere
data_dir: datasets/${data_domain}/${data_type}

# Dataset parameters
ambient_dim: 3
sample: random # can also be 'grid'
n_samples: 1000
task: regression
loss_type: mse
monitor_metric: mae