data_domain: pointcloud
data_type: toy_dataset
data_name: gudhi_torus
data_dir: datasets/${data_domain}/${data_type}

# Dataset parameters
dim: 3 # The dimension of the *torus* - the ambient space has dimension 2 * dim
sample: random # can also be 'grid'
n_samples: 1000
task: regression
loss_type: mse
monitor_metric: mae