data_domain: graph
data_type: QM9
data_name: QM9
data_dir: datasets/${data_domain}/${data_type}
#data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${data_name}

# Dataset parameters
num_features: 11
num_classes: 1
task: regression
loss_type: mse
monitor_metric: mae
task_level: graph

