data_domain: pointcloud
data_type: toy_dataset
data_name: random_dataset
data_dir: datasets/${data_domain}/${data_type}

# Dataset parameters
num_features: 1
num_classes: 2
task: classification
loss_type: cross_entropy
