data_domain: pointcloud
data_type: toy_dataset
data_name: stanford_bunny
data_dir: datasets/${data_domain}/${data_type}/${data_name}

# Dataset parameters
num_classes: 1
task: regression
loss_type: mse
monitor_metric: mae
task_level: graph