data_domain: pointcloud
data_type: UniProt
data_name: UniProt
data_dir: datasets/${data_domain}/${data_type}
#data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${data_name}

# Some parameters to do the query
query: "length:[95 TO 155]" # number of residues per protein
format: "tsv"
fields: "accession,length"
size: 20 # number of proteins to load

# Dataset parameters
num_features: 20
num_classes: 1
task: regression
loss_type: mse
monitor_metric: mae
task_level: graph

